### PR TITLE
Add Linux support to compile default scripts

### PR DESCRIPTION
**Pull request by piepie62**
Simply added a bash file to create the default scripts

### CODE REVIEW

**Comment by BernardoGiordano** [comment]
this is not the smartest idea since scripts would need to be updated in two different places.

**Comment by piepie62** [comment]
I don't understand what you mean

**Comment by SpiredMoth** [comment]
Making new scripts would require editing both the batch and the bash files

**Comment by piepie62** [comment]
Ah, I see

**Comment by trainboy2019** [comment]
Unless we change how we generate scripts, like make a python file to run PKSMScript.py as a function and edit that instead. Just throwing that out there.

**Comment by piepie62** [comment]
I was actually working on a way to do that with bash, but I don't exactly do well with batch scripts. I was going to look up a way to translate it afterwards

**Comment by piepie62** [comment]
A python implementation would work, though.

**Comment by trainboy2019** [comment]
I could try to do that

**Comment by piepie62** [comment]
You could work on it from that angle and we could compare our results afterwards

**Comment by BernardoGiordano** [comment]
I would accept a python script to generate the scripts rather than bash, that way is not restrictive to the os

**Comment by piepie62** [comment]
Okay, that makes sense

**Comment by piepie62** [comment]
I was going to find a batch way to do it after I figured out how to do it in bash, but that works

**Comment by piepie62** [comment]
There, I believe that should work.

**Comment by piepie62** [comment]
The only difference now is that the scripts are put in an external file

**Comment by SpiredMoth** [comment]
Not quite. The scripts were separated by the `@rem <game>` and `move` lines because different games use different offsets for the same data

**Comment by piepie62** [comment]
Oh, yes. I forgot that I removed those lines when I was making this. I can quickly fix that.

**Comment by ihaveamac** [comment]
please switch to use `#!/usr/bin/env python3`, not just "python". these scripts are intended to only work with 3.6+.

**Comment by ihaveamac** [comment]
also, switch it to use "with", and to properly iterate through the lines:
```py
def main(args):
	with open("scripts.txt", 'r') as f:
		for line in f:
			pksmArgs = PKSMScript.parser.parse_args(shlex.split(line))
			PKSMScript.main(pksmArgs)
```

**Comment by piepie62** [comment]
I also decided to remove the shebang line, as that script should not be run outside of the generate scripts

**Comment by ihaveamac** [comment]
Windows accepts / for paths too, but unix/linux systems do not

**Comment by piepie62** [comment]
Ah, okay. Didn't know that.

**Comment by ihaveamac** [comment]
I mean, unix/linux don’t allow \ for paths

**Comment by piepie62** [comment]
Hehe, I understood. In that case I'm going to make it so that any backslashes get changed to forward slashes in order to support all systems.

**Comment by BernardoGiordano** [comment]
😥

**Comment by ihaveamac** [comment]
make sure you have a batch equivalent to the new scripts.sh for Windows users

**Comment by trainboy2019** [comment]
I can't figure out how to do this, I'll leave it up to someone who knows argparse better

**Comment by piepie62** [comment]
I made a batch equivalent, it uses basically the same code from the original.

**Comment by piepie62** [comment]
@trainboy2019 The way that I did it here was that I basically just made a wrapper script that uses the code from the original generator along with the arguments that were being passed in before. I copied the arguments to external files and used those to separate them into different groups, then read from each file and performed the normal logic of PKSMScript on the read arguments.

**Comment by BernardoGiordano** [comment]
Point is you multiplicated the number of files and the .bat/.sh problem is not even solved.

A real solution would be having just two files: 

* PKSMScript.py , that need to be **the same** as the one already available: no changes at all
* generateScripts.py , that calls PKSMScript.py inside of it and creates the needed folder

This is the solution I would merge

**Comment by piepie62** [comment]
Actually, because of the way that it reads the arguments, the batch and bash files do not need to be changed except for if/when there are new games. The current PKSMScript.py is unchanged, and I think that having these different files for the different games is more clear. If you believe that that is not the best idea, I can change it.

**Comment by piepie62** [comment]
The reason I left the batch and bash scripts was because I am fairly unfamiliar with python (thanks for the tips @ihaveamac ) and didn't want to get into file operations. They call genScripts.py and move files, that's it. The reason I separated the arguments for different games into their own files was so that they would be easily differentiable from each other and, instead of editing a python script directly, script creators would edit a separate file that would be less cluttered.

**Comment by ihaveamac** [comment]
separate batch/sh scripts isn't that bad of an idea, since there will never be another Pokémon game for the 3DS. in any case, a "generator" script could also work (preferably along with a simple batch script only to run it)

**Comment by piepie62** [comment]
I believe that is what I have. Can you confirm that, @ihaveamac?

**Comment by SpiredMoth** [comment]
I'm seeing separate batch/sh scripts and a generator script which, as far as I can tell (not being very knowledgeable about batch/sh and Python), does exactly what Bernardo said he wants.

I think what some are missing in regards to the bat is that GitHub is collapsing the large number of changes. The file is still there, just been edited from 332 lines down to 47 lines.

**Comment by piepie62** [comment]
There, I just made it so that genScripts.py does all of the file operations, as well. Instead of deleting the bash and batch files, however, I kept them as ways to run the script.

**Comment by piepie62** [comment]
I also kept the separate script files because I believe that it would be best not to add any complications to the script makers.

**Comment by piepie62** [comment]
By the way, I have not been able to test these changes on Windows computers and I know there are some behavior changes in the file operations. Could one of you please do that for me to make sure that it works properly on Windows?

**Comment by BernardoGiordano** [comment]
I would move all the .txt files into a /src folder, then.. this is probably fine. Also remove the .bat file

**Comment by trainboy2019** [comment]
If this get's pulled, I may try to make PKSMScript.py automatically add the script code to the corresponding .txt file

**Comment by piepie62** [comment]
Alright, that'll be good. Can python files be run directly on Windows? If not, then the batch file should be kept.

**Comment by piepie62** [comment]
@trainboy2019 What do you mean by that?

**Comment by BernardoGiordano** [comment]
@piepie62 sure, command line is enough to run python scripts

**Comment by piepie62** [comment]
Well, I meant just double-clicking on the python file. I know most Windows users are not as good with the command line.

**Comment by BernardoGiordano** [comment]
I should merge trainboy's PR first though. You'll need to update your PR

**Comment by piepie62** [comment]
Alright

**Comment by trainboy2019** [comment]
I mean add an argument called game, where you put the corresponding game name, and it adds it to the txt file. So if the game was usum, it would add the scripts's arguments to scriptsusum.txt as well as make the pksm file for testing

**Comment by BernardoGiordano** [comment]
@trainboy2019 PKSMScript.py mustn't be changed, it's meant to be general purpose

**Comment by piepie62** [comment]
@trainboy2019 That makes sense, but it would also have to delete any duplicates in the scripts text file

**Comment by piepie62** [comment]
Oh, never mind

**Comment by trainboy2019** [comment]
It would just append to the txt file.

**Comment by piepie62** [comment]
For some reason figuring out how to merge that took me WAY too long whoops

**Pull request merged**
