### PR TITLE
single item x999 scripts

### PR DESCRIPTION
**Pull request by SpiredMoth**
High-usage items that the current x99 might be too little of. Willing to take suggestions of others to include in this.

Been holding off on this to save the trouble of merging it into #26 while it's pending.

### CODE REVIEW

**Comment by piepie62** [comment]
It won't be a hard merge, just some copying and pasting. Maybe some type of high-level ball? I'm thinking Ultra or Master. I think maybe the other stat-raising medicines would be good, as well. And in SM/USUM having basically infinite Beast Balls would be cool, as they're normally limited to a certain amount (can't remember the number off the top of my head).

**Comment by SpiredMoth** [comment]
I know it's just some copy/paste stuff, but I'm one of those that likes to minimize the work others have to do because of my contributions.

I have been considering the vitamins, and EV/friendship berries, and I don't mind doing Beast Balls.

Other balls are tricky since we don't want a ton of these single item scripts and people have different opinions on them. Some choose a ball for its capture odds (and different balls are better depending on the situation), some choose for aesthetics. And Master Ball to me has always been one to be wary of since it's often associated with hacked Pokémon.

**Comment by piepie62** [comment]
Alright, that makes sense. And really, I don't mind copying and pasting a few lines of arguments. I like your approach to that, though.

**Comment by BernardoGiordano** [comment]
Fix the PR pleasr

**Comment by SpiredMoth** [comment]
Fixed

**Pull request merged**
